# Use root/example as user/password credentials
version: '3.8'

services:

  app:
    build:
      context: .
    command: bash start.sh
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      GRADLE_USER_HOME: /box
    volumes:
      - .:/reactive-flashcards
      - box:/box
    depends_on:
      - db

  db:
    image: mongo:5.0.9
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: reactive-flashcards
      MONGO_INITDB_ROOT_PASSWORD: reactive-flashcards
      MONGO_INIT_DATABASE: reactive-flashcards
    ports:
      - "27017:27017"

  box:
    image: busybox
    volumes:
      - /box

volumes:
  db:
  box:

#  mongo-express:
#    image: mongo-express
#    restart: always
#    ports:
#      - 8081:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: example
#      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/